// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  image_slice: dynamic(() => import("./ImageSlice")),
  left_image: dynamic(() => import("./LeftImage")),
  prufa: dynamic(() => import("./Prufa")),
  test: dynamic(() => import("./Banner")),
  text: dynamic(() => import("./Text")),
};
